files:
  - source: /kord-extensions/src/main/resources/translations/kordex/strings.properties
    translation: >-
      /kord-extensions/src/main/resources/translations/kordex/%file_name%_%two_letters_code%.%file_extension%
