site:
  baseUrl: "https://kord-extensions.docs.kotlindiscord.com/"
  theme: "Editorial"

  about:
    siteCopyright: "Kotlin Discord"
    siteDescription: "Extensions and commands for Kord"
    siteName: "Kord Extensions"

kotlindoc:
  name: "Kord Extensions"

  modules:
    - name: "Kord Extensions"
      sourceDirs: "./../../../../kord-extensions/src/main/kotlin"
      moduleGroup: "kord-extensions"

  sourcePages:
    menu:
      - type: 'sourcedocPageLinks'
        moduleType: 'kotlindoc'
        itemTitleType: 'SIGNATURE'
        includeItems: true

allPages:
  metaComponents:
    - type: "prism"
      languages:
        - "kotlin"
        - "toml"
        - "yaml"

services:
  publications:
    stages:
      - type: 'githubPages'
        username: 'gdude2002' # the username which created the personal access token
        repo: 'Kotlin-Discord/kord-extensions' # the repo to publish to

wiki:
  defaultConfig:
    createPdf: true

Editorial:
  primaryColor: "#7289DA"
  legacySearch: false

  social:
    github: "Kotlin-Discord/kord-extensions"

  metaComponents:
    - type: "orchidSearch"

  menu:
    - type: 'separator'
      title: 'Wiki'

    - type: 'wiki'

    - type: "separator"
      title: "API Docs"
      
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'

    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'
