site_name: Kord Extensions
site_url: https://kord-extensions.docs.kotlindiscord.com

nav:
  - index.md
  - getting-started.md

  - Concepts:
    - concepts/bot.md
    - concepts/extensions.md
    - concepts/events.md
    - concepts/checks.md
    - concepts/commands.md
    - concepts/converters.md

  - utils.md

  - Integrations:
    - integrations/sentry.md

  - Dokka API Docs: "/-kord%20-extensions/"

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/icon.png

  palette:
    scheme: preference

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - sane_lists
  - toc

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

  - pymdownx.highlight:
      linenums: true

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
