site_name: Kord Extensions
site_url: https://kord-extensions.docs.kotlindiscord.com

repo_name: Kord-Extensions/kord-extensions
repo_url: https://github.com/Kord-Extensions/kord-extensions

nav:
  - index.md
  - getting-started.md

  - Concepts:
      - concepts/bot.md
      - concepts/extensions.md
      - concepts/events.md
      - concepts/checks.md
      - concepts/commands.md
      - concepts/converters.md

  - Utilities:
      - utilities/general.md
      - utilities/paginator.md

  - Integrations:
      - integrations/koin.md
      - integrations/sentry.md

  - Modules:
      - modules/common.md
#      - modules/mappings.md

  - Migrating:
      - migrating/1.4.0.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/icon.png

  icon:
    repo: fontawesome/brands/github

  palette:
    scheme: preference

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - toc.integrate

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

plugins:
  - git-revision-date
  - search

markdown_extensions:
  - admonition
  - attr_list
  - sane_lists

  - mdx_truly_sane_lists

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

  - pymdownx.highlight:
      linenums: true

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - toc:
      permalink: true
