on:
  release:
    types: [published]

jobs:
  relay:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2

        with:
          python-version: 3.x

      - name: Relay release
        run: |
          python .github/relay_release.py
