name: CI

on:
  push:
    branches:
      - "root"
      - "kotlin-1.4"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1.0.0

        with:
          version: 1.11

      - name: Set up Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "githubToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties

      - name: Gradle (Build)
        run: sh gradlew kord-extensions:build docs:orchidBuild

#      - name: Gradle (Deploy docs)
#        run: sh gradlew docs:orchidDeploy

      - name: Gradle (Publish)
        run: sh gradlew -Pkotdis.user=${{ secrets.MAVEN_USER }} -Pkotdis.password=${{ secrets.MAVEN_PASSWORD }} kord-extensions:publish

      - name: Create Docs Zip
        run: |
          zip -r build/docs.zip docs/build/docs/orchid/*

      - name: Upload artifact (JARs)
        uses: actions/upload-artifact@v2

        with:
          name: JARs
          path: kord-extensions/build/libs/kord-extensions-*.jar

      - name: Upload artifact (Docs)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: Docs Zip
          path: build/docs.zip
